import claimAPI from '../api/claimsubmition';
import createDataContext from './createDataContext';
import {
  LOAD_NOTE,
  LOAD_HISTORY,
  LOAD_COMPONENT_FILE,
  ADD_ERROR,
} from '../constant/ActionType';

const policyReducer = (state, action) => {
  switch (action.type) {
    case LOAD_NOTE:
      return {...state, note: action.payload.note};
    case LOAD_COMPONENT_FILE:
      return {
        ...state,
        componentFile: action.payload.componentFile,
      };
    case LOAD_HISTORY:
      return {
        ...state,
        claimHistory: action.payload.claimHistory,
      };
    default:
      return state;
  }
};
// const data = [
//   {
//     noteID: 1,
//     noteDetailId: 1,
//     noteHeader: 'Thời gian yêu cầu bồi thường',
//     noteDetailDesc:
//       'Theo nội dung Điều khoản sản phẩm, thời gian yêu cầu giải quyết quyền lợi bảo hiểm tối đa là 01 năm kể từ khi sự kiện bảo hiểm xảy ra. Công ty sẽ không tiếp nhận hồ sơ đối với các trường hợp vượt quá thời hạn yêu cầu này.',
//     noteOrder: 1,
//   },
//   {
//     noteID: 2,
//     noteDetailId: 2,
//     noteHeader: 'Phương thức nhận tiền',
//     noteDetailDesc:
//       'Quý khách vui lòng gửi kèm bản sao CMND (Còn trong thời hạn 15 năm) của người nhận tiền về công ty. Nếu chọn hình thức chuyển vào tài khoản cá nhân hoặc bưu điện Quý khách phải chịu chi phí chuyển tiền theo quy định của ngân hàng/bưu điện.',
//     noteOrder: 2,
//   },
//   {
//     noteID: 3,
//     noteDetailId: 3,
//     noteHeader: 'Hồ sơ yêu cầu',
//     noteDetailDesc:
//       'Khách hàng vui lòng gửi về công ty bản chính/sao y bản chính tất cả các loại hồ sơ tương ứng với từng loại quyền lợi bảo hiểm theo bảng chi tiết bên dưới (Hợp đồng bảo hiểm chỉ nhận bản chính). Ngoài ra, nếu thấy cần thiết Công ty sẽ yêu cầu khách hàng cung cấp thêm chứng từ khác để việc giải quyết quyền lợi bảo hiểm nhanh chóng và chính',
//     noteOrder: 3,
//   },
// ];
const getNote = dispatch => async () => {
  try {
    const response = await claimAPI.get('/note');
    if (response) {
      dispatch({
        type: LOAD_NOTE,
        payload: {
          //note: response.data,
          note: response.data,
        },
      });
    }
  } catch (err) {
    dispatch({
      type: ADD_ERROR,
      payload: 'Something went wrong!',
    });
  }
};

// const componentfile = [
//   {
//     id: 1,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '1',
//     componentFilename: 'Đơn yêu cầu giải quyết quyền lợi bảo hiểm',
//     accident: '+',
//     pathological: '+',
//     missing: '+',
//     fatalDisease: null,
//   },
//   {
//     id: 2,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '2',
//     componentFilename: 'Giấy chứng tử',
//     accident: '+',
//     pathological: '+',
//     missing: '+',
//     fatalDisease: null,
//   },
//   {
//     id: 3,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '3',
//     componentFilename: 'Giấy báo tử',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 4,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '4',
//     componentFilename: 'Giấy ra viện',
//     accident: '+/-',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 5,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '5',
//     componentFilename: 'Tóm tắt bệnh án/Kết quả xét nghiệm/X-Quang',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 6,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '6',
//     componentFilename: 'Bảng kê chi tiết viện phí',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 7,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '7',
//     componentFilename: 'Hóa đơn viện phí',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 8,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '8',
//     componentFilename:
//       'Bản kết luận về tai nạn, Biên bản/sơ đồ hiện trường, Kết luận pháp y',
//     accident: '+',
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 9,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '9',
//     componentFilename: 'Tường trình về việc tử vong',
//     accident: '+',
//     pathological: '+',
//     missing: '+',
//     fatalDisease: null,
//   },
//   {
//     id: 10,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '10',
//     componentFilename: 'Quyết định tuyên bố tử vong của tòa án',
//     accident: null,
//     pathological: null,
//     missing: '+',
//     fatalDisease: null,
//   },
//   {
//     id: 11,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '11',
//     componentFilename: 'Bộ hợp đồng',
//     accident: '+',
//     pathological: '+',
//     missing: '+',
//     fatalDisease: null,
//   },
//   {
//     id: 12,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '12',
//     componentFilename: 'Hộ khẩu đã xóa tên',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: '+/-',
//     fatalDisease: null,
//   },
//   {
//     id: 13,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '13',
//     componentFilename: 'Giấy tờ chưng minh nhân thân của người thụ hưởng',
//     accident: '+',
//     pathological: '+',
//     missing: '+',
//     fatalDisease: null,
//   },
//   {
//     id: 14,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '14',
//     componentFilename:
//       'Giấy khai sinh người được bảo hiểm/Người thụ hưởng(<18t)',
//     accident: '+',
//     pathological: '+',
//     missing: '+',
//     fatalDisease: null,
//   },
//   {
//     id: 15,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '15',
//     componentFilename: 'Kết quả giám định y khoa',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 16,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '16',
//     componentFilename: 'Biên bản phân chi di sản(Không có người thụ hưởng)',
//     accident: '+',
//     pathological: '+',
//     missing: '+',
//     fatalDisease: null,
//   },
//   {
//     id: 17,
//     componentCode: 'DEAD',
//     componentName: 'Tử vong',
//     colNum: 3,
//     componentFileID: '17',
//     componentFilename:
//       'Quyết định giám hộ hợp pháp(Người được bảo hiểm mất năng lực hành vi dân sự',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 18,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '1',
//     componentFilename: 'Đơn yêu cầu giải quyết quyền lợi bảo hiểm',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: '+',
//   },
//   {
//     id: 19,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '2',
//     componentFilename: 'Giấy chứng tử',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 20,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '3',
//     componentFilename: 'Giấy báo tử',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 21,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '4',
//     componentFilename: 'Giấy ra viện',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: '+',
//   },
//   {
//     id: 22,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '5',
//     componentFilename: 'Tóm tắt bệnh án/Kết quả xét nghiệm/X-Quang',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: '+',
//   },
//   {
//     id: 23,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '6',
//     componentFilename: 'Bảng kê chi tiết viện phí',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: '+/-',
//   },
//   {
//     id: 24,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '7',
//     componentFilename: 'Hóa đơn viện phí',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: '+/-',
//   },
//   {
//     id: 25,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '8',
//     componentFilename:
//       'Bản kết luận về tai nạn, Biên bản/sơ đồ hiện trường, Kết luận pháp y',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 26,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '9',
//     componentFilename: 'Tường trình về việc tử vong',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 27,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '10',
//     componentFilename: 'Quyết định tuyên bố tử vong của tòa án',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 28,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '11',
//     componentFilename: 'Bộ hợp đồng',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 29,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '12',
//     componentFilename: 'Hộ khẩu đã xóa tên',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 30,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '13',
//     componentFilename: 'Giấy tờ chưng minh nhân thân của người thụ hưởng',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: '+',
//   },
//   {
//     id: 31,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '14',
//     componentFilename:
//       'Giấy khai sinh người được bảo hiểm/Người thụ hưởng(<18t)',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 32,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '15',
//     componentFilename: 'Kết quả giám định y khoa',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: '+',
//   },
//   {
//     id: 33,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '16',
//     componentFilename: 'Biên bản phân chi di sản(Không có người thụ hưởng)',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 34,
//     componentCode: 'FTDIS',
//     componentName: 'Bệnh hiểm nghèo',
//     colNum: 1,
//     componentFileID: '17',
//     componentFilename:
//       'Quyết định giám hộ hợp pháp(Người được bảo hiểm mất năng lực hành vi dân sự',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: '+',
//   },
//   {
//     id: 70,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '1',
//     componentFilename: 'Đơn yêu cầu giải quyết quyền lợi bảo hiểm',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 71,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '2',
//     componentFilename: 'Giấy chứng tử',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 72,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '3',
//     componentFilename: 'Giấy báo tử',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 73,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '4',
//     componentFilename: 'Giấy ra viện',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 74,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '5',
//     componentFilename: 'Tóm tắt bệnh án/Kết quả xét nghiệm/X-Quang',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 75,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '6',
//     componentFilename: 'Bảng kê chi tiết viện phí',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 76,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '7',
//     componentFilename: 'Hóa đơn viện phí',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 77,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '8',
//     componentFilename:
//       'Bản kết luận về tai nạn, Biên bản/sơ đồ hiện trường, Kết luận pháp y',
//     accident: '+',
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 78,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '9',
//     componentFilename: 'Tường trình về việc tử vong',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 79,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '10',
//     componentFilename: 'Quyết định tuyên bố tử vong của tòa án',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 80,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '11',
//     componentFilename: 'Bộ hợp đồng',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 81,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '12',
//     componentFilename: 'Hộ khẩu đã xóa tên',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 82,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '13',
//     componentFilename: 'Giấy tờ chưng minh nhân thân của người thụ hưởng',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 83,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '14',
//     componentFilename:
//       'Giấy khai sinh người được bảo hiểm/Người thụ hưởng(<18t)',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 84,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '15',
//     componentFilename: 'Kết quả giám định y khoa',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 85,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '16',
//     componentFilename: 'Biên bản phân chi di sản(Không có người thụ hưởng)',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 86,
//     componentCode: 'GUCHARGE',
//     componentName: 'Từ bỏ thu phí',
//     colNum: 2,
//     componentFileID: '17',
//     componentFilename:
//       'Quyết định giám hộ hợp pháp(Người được bảo hiểm mất năng lực hành vi dân sự',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 36,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '1',
//     componentFilename: 'Đơn yêu cầu giải quyết quyền lợi bảo hiểm',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 37,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '2',
//     componentFilename: 'Giấy chứng tử',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 38,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '3',
//     componentFilename: 'Giấy báo tử',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 39,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '4',
//     componentFilename: 'Giấy ra viện',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 40,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '5',
//     componentFilename: 'Tóm tắt bệnh án/Kết quả xét nghiệm/X-Quang',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 41,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '6',
//     componentFilename: 'Bảng kê chi tiết viện phí',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 42,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '7',
//     componentFilename: 'Hóa đơn viện phí',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 43,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '8',
//     componentFilename:
//       'Bản kết luận về tai nạn, Biên bản/sơ đồ hiện trường, Kết luận pháp y',
//     accident: '+/-',
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 44,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '9',
//     componentFilename: 'Tường trình về việc tử vong',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 45,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '10',
//     componentFilename: 'Quyết định tuyên bố tử vong của tòa án',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 46,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '11',
//     componentFilename: 'Bộ hợp đồng',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 47,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '12',
//     componentFilename: 'Hộ khẩu đã xóa tên',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 48,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '13',
//     componentFilename: 'Giấy tờ chưng minh nhân thân của người thụ hưởng',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 49,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '14',
//     componentFilename:
//       'Giấy khai sinh người được bảo hiểm/Người thụ hưởng(<18t)',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 50,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '15',
//     componentFilename: 'Kết quả giám định y khoa',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 51,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '16',
//     componentFilename: 'Biên bản phân chi di sản(Không có người thụ hưởng)',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 52,
//     componentCode: 'HOSFASS',
//     componentName: 'Hỗ trợ chi phí nằm viện',
//     colNum: 2,
//     componentFileID: '17',
//     componentFilename:
//       'Quyết định giám hộ hợp pháp(Người được bảo hiểm mất năng lực hành vi dân sự',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 53,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '1',
//     componentFilename: 'Đơn yêu cầu giải quyết quyền lợi bảo hiểm',
//     accident: '+',
//     pathological: '+',
//     missing: 'NILL',
//     fatalDisease: null,
//   },
//   {
//     id: 54,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '2',
//     componentFilename: 'Giấy chứng tử',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 55,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '3',
//     componentFilename: 'Giấy báo tử',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 56,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '4',
//     componentFilename: 'Giấy ra viện',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 57,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '5',
//     componentFilename: 'Tóm tắt bệnh án/Kết quả xét nghiệm/X-Quang',
//     accident: '+',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 58,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '6',
//     componentFilename: 'Bảng kê chi tiết viện phí',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 59,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '7',
//     componentFilename: 'Hóa đơn viện phí',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 60,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '8',
//     componentFilename:
//       'Bản kết luận về tai nạn, Biên bản/sơ đồ hiện trường, Kết luận pháp y',
//     accident: '+',
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 61,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '9',
//     componentFilename: 'Tường trình về việc tử vong',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 62,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '10',
//     componentFilename: 'Quyết định tuyên bố tử vong của tòa án',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 63,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '11',
//     componentFilename: 'Bộ hợp đồng',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 64,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '12',
//     componentFilename: 'Hộ khẩu đã xóa tên',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 65,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '13',
//     componentFilename: 'Giấy tờ chưng minh nhân thân của người thụ hưởng',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 66,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '14',
//     componentFilename:
//       'Giấy khai sinh người được bảo hiểm/Người thụ hưởng(<18t)',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 67,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '15',
//     componentFilename: 'Kết quả giám định y khoa',
//     accident: '+/-',
//     pathological: '+/-',
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 68,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '16',
//     componentFilename: 'Biên bản phân chi di sản(Không có người thụ hưởng)',
//     accident: null,
//     pathological: null,
//     missing: null,
//     fatalDisease: null,
//   },
//   {
//     id: 69,
//     componentCode: 'INJERED',
//     componentName: 'Thương tật',
//     colNum: 2,
//     componentFileID: '17',
//     componentFilename:
//       'Quyết định giám hộ hợp pháp(Người được bảo hiểm mất năng lực hành vi dân sự',
//     accident: '+',
//     pathological: '+',
//     missing: null,
//     fatalDisease: null,
//   },
// ];
const getcomponentFile = dispatch => async () => {
  try {
    const response = await claimAPI.get('/componentfile');
    if (response) {
      dispatch({
        type: LOAD_COMPONENT_FILE,
        payload: {
          // componentFile: response.data,
          componentFile: response.data,
        },
      });
    }
  } catch (err) {
    dispatch({
      type: ADD_ERROR,
      payload: 'Something went wrong!',
    });
  }
};
const history = [
  {
    tranno: 39,
    policyNumber: '80004153',
    componentName: 'Hỗ trợ chi phí nằm viện',
    claimHistory: 'BT',
    clmSubmitDate: '09-11-2017',
    clmOccurDate: '13-10-2017',
  },
  {
    tranno: 40,
    policyNumber: '80004153',
    componentName: 'Hỗ trợ chi phí nằm viện',
    claimHistory: 'BT',
    clmSubmitDate: '31-12-2017',
    clmOccurDate: '06-12-2017',
  },
  {
    tranno: 58,
    policyNumber: '80004153',
    componentName: 'Hỗ trợ chi phí nằm viện',
    claimHistory: 'MT',
    clmSubmitDate: '25-06-2018',
    clmOccurDate: '30-04-2018',
  },
  {
    tranno: 59,
    policyNumber: '80004153',
    componentName: 'Hỗ trợ chi phí nằm viện',
    claimHistory: 'MT',
    clmSubmitDate: '25-06-2018',
    clmOccurDate: '30-05-2018',
  },
  {
    tranno: 65,
    policyNumber: '80004153',
    componentName: 'Hỗ trợ chi phí nằm viện',
    claimHistory: 'BT',
    clmSubmitDate: '22-06-2018',
    clmOccurDate: '30-04-2018',
  },
];
const getClaimHistory = dispatch => async poNumber => {
  try {
    console.log('getClaimFuntion: ', poNumber);
    const response = history; //await claimAPI.get(`/policyhistory/${poNumber}`);
    dispatch({
      type: LOAD_HISTORY,
      payload: {
        // componentFile: response.data,
        claimHistory: response,
      },
    });
  } catch (err) {
    dispatch({
      type: ADD_ERROR,
      payload: 'Something went wrong!',
    });
  }
};

export const {Provider, Context} = createDataContext(
  policyReducer,
  {getNote, getcomponentFile, getClaimHistory},
  {
    note: [],
    componentFile: [],
    claimHistory: [],
  },
);
